# basic options
title: Cian White
author: ciwhite
email: ciwhite@tcd.ie
description: Personal webpage of Cian White
twitter_username: CianDeFaoiche
github_username: ciwhite

# Build Settings
markdown: kramdown
theme: minima
