# basic options
title: Smooth Criminal
author: ciwhite
email: ciwhite@tcd.ie
description: This wonderful life deserves a smooth digital representation
twitter_username: CianDeFaoiche
github_username: ciwhite

# Build Settings
markdown: kramdown
theme: minima
